title: Alva Vially
url: https://alva.vially.fr
author: Alva Vially

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename"
  -
    scope:
      path: "articles/_posts"
    values:
      layout: "article"
      permalink: "/:categories/:title"
  -
    scope:
      path: "updates/_posts"
    values:
      layout: "update"
      permalink: "/:categories/:year/:month/:day/:title"
  -
    scope:
      path: "projects/_posts"
    values:
      layout: "project"
      permalink: "/:categories/:title"
  
exclude: 
  - assets/img/projects/*.png

feed:
  categories:
    - articles
    - projects
    - updates