title: Alva Vially
url: https://alva.vially.fr
author: Alva Vially

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_articles"
    values:
      layout: "article"
  -
    scope:
      path: "_posts"
    values:
      layout: "update"
  -
    scope:
      path: "_projects"
    values:
      layout: "project"

collections:
  articles:
    output: true
    sort_by: update
  projects:
    output: true
  
exclude: 
  - assets/img/projects/*.png

feed:
  collections:
    - projects
    - articles